Update dependencies installation on CentOS
zonemaster/zonemaster-cli pull request #188
Opened 2021-01-20 15:45 UTC by mattias-p

* Replace MooseX::Getopt with perl-MooseX-Getopt
* Remove Locale::MsgFmt (not used)
* Remove Locale::TextDomain (use the same one as Engine)
* Work around compolation errors on CentOS 8

2021-01-20 15:53 UTC, matsduf requested changes
Since the work-around is only needed for CentOS 8 I think that CentOS 7 should have a normal installation.

2021-01-20 16:03 UTC, mattias-p commented
Are you sure? In my opinion it's more important that the installation instructions are easy to follow and maintain than that they result in the perfect installation. I'd prefer if users could just breeze through the installation as much as possible and stop and think as little as possible. I think we should prioritize onboarding.

2021-01-20 16:33 UTC, matsduf commented
> Are you sure? In my opinion it's more important that the installation instructions are easy to follow and maintain than that they result in the perfect installation. I'd prefer if users could just breeze through the installation as much as possible and stop and think as little as possible. I think we should prioritize onboarding.

That is not how we have done for Zonemaster-Engine and Zonemaster-Backend. I think that has worked well.

2021-01-25 13:34 UTC, matsduf approved these changes

2021-01-25 15:06 UTC, pnax approved these changes

2021-01-25 15:20 UTC, merged