Preparation for release v2023.1.4 (CLI)
zonemaster/zonemaster-cli pull request #352
Opened 2023-09-01 09:14 UTC by matsduf

## Purpose

Preparation for release.

## Changes

Updates files `Changes`, `Makefile.PL` and `CLI.pm`.

## How to test this PR

Review the changes.

2023-09-01 16:25 UTC, mattias-p approved these changes

2023-09-04 09:13 UTC, marc-vanderwal approved these changes

2023-09-04 10:24 UTC, pnax requested changes

2023-09-04 10:24 UTC, pnax commented on Changes
> +   require a higher (fixed) version of Zonemaster-Engine.
Please include https://github.com/zonemaster/zonemaster-cli/pull/351.

2023-09-04 20:38 UTC, mattias-p commented on Changes
> + - Fixes a spelling error (text) in the zonemaster-cli scrip (#351).
```suggestion
 - Fixes a spelling error (text) in the zonemaster-cli script (#351).
```

2023-09-04 20:40 UTC, mattias-p approved these changes

2023-09-05 05:40 UTC, marc-vanderwal approved these changes

2023-09-05 20:19 UTC, matsduf commented
@pnax, please re-review.

2023-09-06 07:59 UTC, pnax reviewed
beside the date, lgtm

2023-09-06 07:59 UTC, pnax commented on Changes
> +v6.0.3 2023-09-05 (public fix version)
Shouldn't the date be updated?

2023-09-07 05:58 UTC, marc-vanderwal approved these changes

2023-09-07 06:06 UTC, marc-vanderwal commented on Changes
> +v6.0.3 2023-09-05 (public fix version)
The date has been changed.

2023-09-07 11:40 UTC, merged